[package]
name = "rp2040-fw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
embedded-hal = { version = "0.2.5", features = ["unproven"] }
embedded-time = "0.12.0"

defmt = "0.3.0"
defmt-rtt = "0.3.0"
panic-probe = { version = "0.3.0", features = ["print-defmt"] }

rp-pico = "0.3.0"

rp2040-hal = { version="0.4.0", features=["rt"] }
rp2040-boot2 = "0.2.0"

usb-device = "0.2.8"
usbd-hid = "0.6.0"

rotary-encoder-embedded = "0.1.0"
